# Generated by Django 5.1.1 on 2024-10-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
