# Generated by Django 5.1.1 on 2024-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invApp", "0002_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(),
        ),
    ]
